### PR TITLE
Update to 63.4.1

### PR DESCRIPTION
**Pull request by Arishamays1**
Version bump to 63.4.1.
- updated sha256
- added and updated patches

Reviewed the upstream changelog and found two breaking changes since the last update (61.2.0).
- https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6300
- https://github.com/pypa/setuptools/blob/main/CHANGES.rst#breaking-changes-1

We determined that these changes should not impact us.

### CODE REVIEW

**Review by katietz — CHANGES_REQUESTED** [review]
The changes itself are looking good to me, thanks.
One question about testing.  As there were breaking changes for entry-point creation inbetween of those version, I would be interested to learn how you made sure there are not regression for our entry-point recipes?  Have you can tests for it? if so please let people know which tests you did.

**Comment by Arishamays1** [comment]
> 

Thanks Kai. After going back and testing the the compatibility of `setuptools v63.4.1` with packages that contain entry_point within their recipes, I found that there are not issues or discrepancies in their functionality.

**Review by varlackc — COMMENTED** [review]
There are a lot of packages that depend on `setuptools` if there is a regression introduced by mistake in `setuptools` it has the potential to break a lot of our packages.

Is there a particular package that requires this version of `setuptools`?

**Review by cbouss — APPROVED** [review]
Regarding the breaking change on entrypoints:
```
Breaking Changes
#3421: Drop setuptools' support for installing an entrypoint extra requirements at load time: - the functionality has been broken since v60.8.0. - the mechanism to do so is deprecated (fetch_build_eggs). - that use case (e.g. a custom command class entrypoint) is covered by making sure the necessary build requirements are declared.
```

This has been broken since v60.8.0. The current setuptools in default is 61.2.0, which means this feature is already not working.

If you look at the actual issue on setuptools:
https://github.com/pypa/setuptools/pull/3421
This feature was installing dependencies of extras entrypoints. This is something that we would want to avoid anyway, since we want dependencies resolved through conda.

Given all the above, LGTM

**Comment by Arishamays1** [comment]
> There are a lot of packages that depend on `setuptools` if there is a regression introduced by mistake in `setuptools` it has the potential to break a lot of our packages.
> 
> Is there a particular package that requires this version of `setuptools`?

I definitely understand this being a concern. Prior to this PR, our repo's version of `setuptools` was noticeably outdated and I am concerned that potential packages that depend on `setuptools`, might require its newest release in the near future.

**Comment by varlackc** [comment]
> > There are a lot of packages that depend on `setuptools` if there is a regression introduced by mistake in `setuptools` it has the potential to break a lot of our packages.
> > Is there a particular package that requires this version of `setuptools`?
> 
> I definitely understand this being a concern. Prior to this PR, our repo's version of `setuptools` was noticeably outdated and I am concerned that potential packages that depend on `setuptools`, might require its newest release in the near future.

We currently have more than `400` packages that depend on `setuptools`. If we introduce a regresion by accident in `setuptools` there is a high chance that a large number of such packages could be affected. We might need to discuss the update of `setuptools` as a team before updating.

**Pull request merged**
