### PR TITLE
Update 58.0.4

### PR DESCRIPTION
**Pull request by katietz**

### CODE REVIEW

**Comment by katietz** [comment]
The build fail as the environment variable CONDA_ADD_PIP_AS_PYTHON_DEPENDENCY isn't set to 0.  This is required for certifi, wincert..., wheel, pip, and setuptools to avoid this issue.

**Comment by katietz** [comment]
as side-note: I built all packages on the architectures above manually successful.  They are already on defaults now

**Comment by dbast** [comment]
Should be correctly set, see https://github.com/ContinuumIO/docker-images/blob/master/anaconda-pkg-build/linux/Dockerfile#L115

Build log tells that "patch" is missing.

**Comment by katietz** [comment]
yeah, it was yesterday a bit too late here.  added patch tool, and it works now fine.  So on c3i we have actually patch being pre-installed.

**Pull request merged**
